# This is a basic workflow to help you get started with Actions
 
name:
  First Cron Job
 
  # Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/2 * * * *"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Runs stuff
      - name: Run stuff
        run: |
          echo Hello, world!
          dd=$(date | sed 's/ /-/g')
          echo Ciaociao > out-$dd.txt
          date >> out-$dd.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "twincacca"
          git config --global user.email "twincacca@gmail.com"
          git add .
          git commit -m "commit message xxx"
          git push
